# Generated by Django 4.0.6 on 2022-07-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Asset_Type', models.CharField(max_length=25)),
                ('Asset_Name', models.CharField(max_length=25)),
                ('Serial_No', models.PositiveIntegerField()),
                ('Mac_address', models.CharField(max_length=30)),
                ('Memmory_Size', models.PositiveIntegerField()),
                ('HHD_Size', models.PositiveIntegerField()),
                ('Asset_Model', models.CharField(max_length=25)),
            ],
        ),
    ]
