# Generated by Django 4.0.6 on 2022-07-16 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokka', '0002_alter_product_asset_model_alter_product_asset_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
