# Generated by Django 4.0.6 on 2022-07-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokka', '0003_product_time_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Power_capacity',
            field=models.IntegerField(default=0),
        ),
    ]
